name: habio_professional
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_functions: ^6.0.2

  google_maps_flutter: ^2.18.0
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  cloud_firestore: ^6.8.0
  crypto: ^3.0.7
  firebase_storage: ^13.4.6
  file_picker: ^12.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true