// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Sv_OCTaL3GT-3c7TqBC81G2gwnJC70E',
    appId: '1:508954448154:web:d0ba299645ce0492f69ca3',
    messagingSenderId: '508954448154',
    projectId: 'project-x-development',
    authDomain: 'project-x-development.firebaseapp.com',
    storageBucket: 'project-x-development.firebasestorage.app',
    measurementId: 'G-5MR18HYZJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtdx93sRw7hzk8SJLU-uR63QLDsv-ZvM',
    appId: '1:508954448154:android:a7bd5da7be596448f69ca3',
    messagingSenderId: '508954448154',
    projectId: 'project-x-development',
    storageBucket: 'project-x-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsiKgN94eMjZJLdqyynwErLd0glZSg3Zg',
    appId: '1:508954448154:ios:a762181e32518c5ef69ca3',
    messagingSenderId: '508954448154',
    projectId: 'project-x-development',
    storageBucket: 'project-x-development.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsiKgN94eMjZJLdqyynwErLd0glZSg3Zg',
    appId: '1:508954448154:ios:a762181e32518c5ef69ca3',
    messagingSenderId: '508954448154',
    projectId: 'project-x-development',
    storageBucket: 'project-x-development.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Sv_OCTaL3GT-3c7TqBC81G2gwnJC70E',
    appId: '1:508954448154:web:991ef0674124f046f69ca3',
    messagingSenderId: '508954448154',
    projectId: 'project-x-development',
    authDomain: 'project-x-development.firebaseapp.com',
    storageBucket: 'project-x-development.firebasestorage.app',
    measurementId: 'G-EWXD1YXGP1',
  );
}
